// flow-typed signature: 183548757f0fce78f608e6ef9b95e3d2
// flow-typed version: <<STUB>>/face-api.js_v^0.20.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'face-api.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'face-api.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'face-api.js/build/commonjs/ageGenderNet/AgeGenderNet' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/ageGenderNet/extractParams' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/ageGenderNet/extractParamsFromWeigthMap' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/ageGenderNet/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/ageGenderNet/types' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/classes/FaceDetection' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/classes/FaceLandmarks' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/classes/FaceLandmarks5' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/classes/FaceLandmarks68' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/classes/FaceMatch' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/classes/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/classes/LabeledFaceDescriptors' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/common/depthwiseSeparableConv' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/common/fullyConnectedLayer' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/common/loadConvParamsFactory' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/dom/extractFaces' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/dom/extractFaceTensors' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/dom/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/draw/drawContour' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/draw/drawDetections' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/draw/drawFaceExpressions' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/draw/DrawFaceLandmarks' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/draw/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/euclideanDistance' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceExpressionNet/FaceExpressionNet' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceExpressionNet/FaceExpressions' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceExpressionNet/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceFeatureExtractor/denseBlock' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceFeatureExtractor/extractorsFactory' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceFeatureExtractor/extractParams' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceFeatureExtractor/extractParamsFromWeigthMap' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceFeatureExtractor/extractParamsFromWeigthMapTiny' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceFeatureExtractor/extractParamsTiny' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceFeatureExtractor/FaceFeatureExtractor' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceFeatureExtractor/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceFeatureExtractor/loadParamsFactory' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceFeatureExtractor/TinyFaceFeatureExtractor' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceFeatureExtractor/types' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceLandmarkNet/FaceLandmark68Net' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceLandmarkNet/FaceLandmark68NetBase' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceLandmarkNet/FaceLandmark68TinyNet' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceLandmarkNet/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceProcessor/extractParams' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceProcessor/extractParamsFromWeigthMap' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceProcessor/FaceProcessor' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceProcessor/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceProcessor/types' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceProcessor/util' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceRecognitionNet/convLayer' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceRecognitionNet/extractParams' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceRecognitionNet/extractParamsFromWeigthMap' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceRecognitionNet/FaceRecognitionNet' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceRecognitionNet/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceRecognitionNet/residualLayer' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceRecognitionNet/scaleLayer' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/faceRecognitionNet/types' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/factories/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/factories/WithAge' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/factories/WithFaceDescriptor' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/factories/WithFaceDetection' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/factories/WithFaceExpressions' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/factories/WithFaceLandmarks' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/factories/WithGender' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/globalApi/allFaces' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/globalApi/ComposableTask' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/globalApi/ComputeFaceDescriptorsTasks' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/globalApi/DetectFaceLandmarksTasks' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/globalApi/detectFaces' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/globalApi/DetectFacesTasks' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/globalApi/extractFacesAndComputeResults' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/globalApi/FaceMatcher' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/globalApi/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/globalApi/nets' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/globalApi/PredictAgeAndGenderTask' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/globalApi/PredictFaceExpressionsTask' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/globalApi/types' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/minBbox' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/bgrToRgbTensor' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/config' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/extractImagePatches' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/extractParams' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/extractParamsFromWeigthMap' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/getSizesForScale' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/Mtcnn' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/MtcnnBox' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/MtcnnOptions' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/normalize' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/ONet' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/PNet' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/prelu' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/pyramidDown' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/RNet' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/sharedLayers' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/stage1' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/stage2' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/stage3' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/mtcnn/types' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/resizeResults' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/ssdMobilenetv1/boxPredictionLayer' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/ssdMobilenetv1/extractParams' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/ssdMobilenetv1/extractParamsFromWeigthMap' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/ssdMobilenetv1/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/ssdMobilenetv1/mobileNetV1' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/ssdMobilenetv1/nonMaxSuppression' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/ssdMobilenetv1/outputLayer' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/ssdMobilenetv1/pointwiseConvLayer' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/ssdMobilenetv1/predictionLayer' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/ssdMobilenetv1/SsdMobilenetv1' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/ssdMobilenetv1/SsdMobilenetv1Options' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/ssdMobilenetv1/types' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/tinyFaceDetector/const' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/tinyFaceDetector/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/tinyFaceDetector/TinyFaceDetector' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/tinyFaceDetector/TinyFaceDetectorOptions' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/tinyYolov2/const' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/tinyYolov2/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/tinyYolov2/TinyYolov2' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/xception/extractParams' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/xception/extractParamsFromWeigthMap' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/xception/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/xception/TinyXception' {
  declare module.exports: any;
}

declare module 'face-api.js/build/commonjs/xception/types' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/ageGenderNet/AgeGenderNet' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/ageGenderNet/extractParams' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/ageGenderNet/extractParamsFromWeigthMap' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/ageGenderNet/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/ageGenderNet/types' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/classes/FaceDetection' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/classes/FaceLandmarks' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/classes/FaceLandmarks5' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/classes/FaceLandmarks68' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/classes/FaceMatch' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/classes/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/classes/LabeledFaceDescriptors' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/common/depthwiseSeparableConv' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/common/fullyConnectedLayer' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/common/loadConvParamsFactory' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/dom/extractFaces' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/dom/extractFaceTensors' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/dom/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/draw/drawContour' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/draw/drawDetections' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/draw/drawFaceExpressions' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/draw/DrawFaceLandmarks' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/draw/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/euclideanDistance' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceExpressionNet/FaceExpressionNet' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceExpressionNet/FaceExpressions' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceExpressionNet/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceFeatureExtractor/denseBlock' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceFeatureExtractor/extractorsFactory' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceFeatureExtractor/extractParams' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceFeatureExtractor/extractParamsFromWeigthMap' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceFeatureExtractor/extractParamsFromWeigthMapTiny' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceFeatureExtractor/extractParamsTiny' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceFeatureExtractor/FaceFeatureExtractor' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceFeatureExtractor/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceFeatureExtractor/loadParamsFactory' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceFeatureExtractor/TinyFaceFeatureExtractor' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceFeatureExtractor/types' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceLandmarkNet/FaceLandmark68Net' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceLandmarkNet/FaceLandmark68NetBase' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceLandmarkNet/FaceLandmark68TinyNet' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceLandmarkNet/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceProcessor/extractParams' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceProcessor/extractParamsFromWeigthMap' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceProcessor/FaceProcessor' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceProcessor/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceProcessor/types' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceProcessor/util' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceRecognitionNet/convLayer' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceRecognitionNet/extractParams' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceRecognitionNet/extractParamsFromWeigthMap' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceRecognitionNet/FaceRecognitionNet' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceRecognitionNet/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceRecognitionNet/residualLayer' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceRecognitionNet/scaleLayer' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/faceRecognitionNet/types' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/factories/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/factories/WithAge' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/factories/WithFaceDescriptor' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/factories/WithFaceDetection' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/factories/WithFaceExpressions' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/factories/WithFaceLandmarks' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/factories/WithGender' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/globalApi/allFaces' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/globalApi/ComposableTask' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/globalApi/ComputeFaceDescriptorsTasks' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/globalApi/DetectFaceLandmarksTasks' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/globalApi/detectFaces' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/globalApi/DetectFacesTasks' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/globalApi/extractFacesAndComputeResults' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/globalApi/FaceMatcher' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/globalApi/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/globalApi/nets' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/globalApi/PredictAgeAndGenderTask' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/globalApi/PredictFaceExpressionsTask' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/globalApi/types' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/minBbox' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/bgrToRgbTensor' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/config' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/extractImagePatches' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/extractParams' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/extractParamsFromWeigthMap' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/getSizesForScale' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/Mtcnn' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/MtcnnBox' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/MtcnnOptions' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/normalize' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/ONet' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/PNet' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/prelu' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/pyramidDown' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/RNet' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/sharedLayers' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/stage1' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/stage2' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/stage3' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/mtcnn/types' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/resizeResults' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/ssdMobilenetv1/boxPredictionLayer' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/ssdMobilenetv1/extractParams' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/ssdMobilenetv1/extractParamsFromWeigthMap' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/ssdMobilenetv1/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/ssdMobilenetv1/mobileNetV1' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/ssdMobilenetv1/nonMaxSuppression' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/ssdMobilenetv1/outputLayer' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/ssdMobilenetv1/pointwiseConvLayer' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/ssdMobilenetv1/predictionLayer' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/ssdMobilenetv1/SsdMobilenetv1' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/ssdMobilenetv1/SsdMobilenetv1Options' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/ssdMobilenetv1/types' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/tinyFaceDetector/const' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/tinyFaceDetector/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/tinyFaceDetector/TinyFaceDetector' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/tinyFaceDetector/TinyFaceDetectorOptions' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/tinyYolov2/const' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/tinyYolov2/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/tinyYolov2/TinyYolov2' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/xception/extractParams' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/xception/extractParamsFromWeigthMap' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/xception/index' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/xception/TinyXception' {
  declare module.exports: any;
}

declare module 'face-api.js/build/es6/xception/types' {
  declare module.exports: any;
}

declare module 'face-api.js/dist/face-api' {
  declare module.exports: any;
}

declare module 'face-api.js/dist/face-api.min' {
  declare module.exports: any;
}

declare module 'face-api.js/jasmine-node' {
  declare module.exports: any;
}

declare module 'face-api.js/karma.conf' {
  declare module.exports: any;
}

declare module 'face-api.js/rollup.config' {
  declare module.exports: any;
}

declare module 'face-api.js/typedoc.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'face-api.js/build/commonjs/ageGenderNet/AgeGenderNet.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/ageGenderNet/AgeGenderNet'>;
}
declare module 'face-api.js/build/commonjs/ageGenderNet/extractParams.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/ageGenderNet/extractParams'>;
}
declare module 'face-api.js/build/commonjs/ageGenderNet/extractParamsFromWeigthMap.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/ageGenderNet/extractParamsFromWeigthMap'>;
}
declare module 'face-api.js/build/commonjs/ageGenderNet/index.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/ageGenderNet/index'>;
}
declare module 'face-api.js/build/commonjs/ageGenderNet/types.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/ageGenderNet/types'>;
}
declare module 'face-api.js/build/commonjs/classes/FaceDetection.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/classes/FaceDetection'>;
}
declare module 'face-api.js/build/commonjs/classes/FaceLandmarks.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/classes/FaceLandmarks'>;
}
declare module 'face-api.js/build/commonjs/classes/FaceLandmarks5.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/classes/FaceLandmarks5'>;
}
declare module 'face-api.js/build/commonjs/classes/FaceLandmarks68.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/classes/FaceLandmarks68'>;
}
declare module 'face-api.js/build/commonjs/classes/FaceMatch.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/classes/FaceMatch'>;
}
declare module 'face-api.js/build/commonjs/classes/index.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/classes/index'>;
}
declare module 'face-api.js/build/commonjs/classes/LabeledFaceDescriptors.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/classes/LabeledFaceDescriptors'>;
}
declare module 'face-api.js/build/commonjs/common/depthwiseSeparableConv.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/common/depthwiseSeparableConv'>;
}
declare module 'face-api.js/build/commonjs/common/fullyConnectedLayer.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/common/fullyConnectedLayer'>;
}
declare module 'face-api.js/build/commonjs/common/loadConvParamsFactory.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/common/loadConvParamsFactory'>;
}
declare module 'face-api.js/build/commonjs/dom/extractFaces.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/dom/extractFaces'>;
}
declare module 'face-api.js/build/commonjs/dom/extractFaceTensors.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/dom/extractFaceTensors'>;
}
declare module 'face-api.js/build/commonjs/dom/index.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/dom/index'>;
}
declare module 'face-api.js/build/commonjs/draw/drawContour.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/draw/drawContour'>;
}
declare module 'face-api.js/build/commonjs/draw/drawDetections.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/draw/drawDetections'>;
}
declare module 'face-api.js/build/commonjs/draw/drawFaceExpressions.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/draw/drawFaceExpressions'>;
}
declare module 'face-api.js/build/commonjs/draw/DrawFaceLandmarks.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/draw/DrawFaceLandmarks'>;
}
declare module 'face-api.js/build/commonjs/draw/index.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/draw/index'>;
}
declare module 'face-api.js/build/commonjs/euclideanDistance.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/euclideanDistance'>;
}
declare module 'face-api.js/build/commonjs/faceExpressionNet/FaceExpressionNet.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceExpressionNet/FaceExpressionNet'>;
}
declare module 'face-api.js/build/commonjs/faceExpressionNet/FaceExpressions.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceExpressionNet/FaceExpressions'>;
}
declare module 'face-api.js/build/commonjs/faceExpressionNet/index.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceExpressionNet/index'>;
}
declare module 'face-api.js/build/commonjs/faceFeatureExtractor/denseBlock.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceFeatureExtractor/denseBlock'>;
}
declare module 'face-api.js/build/commonjs/faceFeatureExtractor/extractorsFactory.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceFeatureExtractor/extractorsFactory'>;
}
declare module 'face-api.js/build/commonjs/faceFeatureExtractor/extractParams.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceFeatureExtractor/extractParams'>;
}
declare module 'face-api.js/build/commonjs/faceFeatureExtractor/extractParamsFromWeigthMap.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceFeatureExtractor/extractParamsFromWeigthMap'>;
}
declare module 'face-api.js/build/commonjs/faceFeatureExtractor/extractParamsFromWeigthMapTiny.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceFeatureExtractor/extractParamsFromWeigthMapTiny'>;
}
declare module 'face-api.js/build/commonjs/faceFeatureExtractor/extractParamsTiny.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceFeatureExtractor/extractParamsTiny'>;
}
declare module 'face-api.js/build/commonjs/faceFeatureExtractor/FaceFeatureExtractor.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceFeatureExtractor/FaceFeatureExtractor'>;
}
declare module 'face-api.js/build/commonjs/faceFeatureExtractor/index.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceFeatureExtractor/index'>;
}
declare module 'face-api.js/build/commonjs/faceFeatureExtractor/loadParamsFactory.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceFeatureExtractor/loadParamsFactory'>;
}
declare module 'face-api.js/build/commonjs/faceFeatureExtractor/TinyFaceFeatureExtractor.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceFeatureExtractor/TinyFaceFeatureExtractor'>;
}
declare module 'face-api.js/build/commonjs/faceFeatureExtractor/types.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceFeatureExtractor/types'>;
}
declare module 'face-api.js/build/commonjs/faceLandmarkNet/FaceLandmark68Net.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceLandmarkNet/FaceLandmark68Net'>;
}
declare module 'face-api.js/build/commonjs/faceLandmarkNet/FaceLandmark68NetBase.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceLandmarkNet/FaceLandmark68NetBase'>;
}
declare module 'face-api.js/build/commonjs/faceLandmarkNet/FaceLandmark68TinyNet.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceLandmarkNet/FaceLandmark68TinyNet'>;
}
declare module 'face-api.js/build/commonjs/faceLandmarkNet/index.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceLandmarkNet/index'>;
}
declare module 'face-api.js/build/commonjs/faceProcessor/extractParams.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceProcessor/extractParams'>;
}
declare module 'face-api.js/build/commonjs/faceProcessor/extractParamsFromWeigthMap.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceProcessor/extractParamsFromWeigthMap'>;
}
declare module 'face-api.js/build/commonjs/faceProcessor/FaceProcessor.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceProcessor/FaceProcessor'>;
}
declare module 'face-api.js/build/commonjs/faceProcessor/index.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceProcessor/index'>;
}
declare module 'face-api.js/build/commonjs/faceProcessor/types.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceProcessor/types'>;
}
declare module 'face-api.js/build/commonjs/faceProcessor/util.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceProcessor/util'>;
}
declare module 'face-api.js/build/commonjs/faceRecognitionNet/convLayer.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceRecognitionNet/convLayer'>;
}
declare module 'face-api.js/build/commonjs/faceRecognitionNet/extractParams.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceRecognitionNet/extractParams'>;
}
declare module 'face-api.js/build/commonjs/faceRecognitionNet/extractParamsFromWeigthMap.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceRecognitionNet/extractParamsFromWeigthMap'>;
}
declare module 'face-api.js/build/commonjs/faceRecognitionNet/FaceRecognitionNet.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceRecognitionNet/FaceRecognitionNet'>;
}
declare module 'face-api.js/build/commonjs/faceRecognitionNet/index.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceRecognitionNet/index'>;
}
declare module 'face-api.js/build/commonjs/faceRecognitionNet/residualLayer.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceRecognitionNet/residualLayer'>;
}
declare module 'face-api.js/build/commonjs/faceRecognitionNet/scaleLayer.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceRecognitionNet/scaleLayer'>;
}
declare module 'face-api.js/build/commonjs/faceRecognitionNet/types.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/faceRecognitionNet/types'>;
}
declare module 'face-api.js/build/commonjs/factories/index.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/factories/index'>;
}
declare module 'face-api.js/build/commonjs/factories/WithAge.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/factories/WithAge'>;
}
declare module 'face-api.js/build/commonjs/factories/WithFaceDescriptor.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/factories/WithFaceDescriptor'>;
}
declare module 'face-api.js/build/commonjs/factories/WithFaceDetection.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/factories/WithFaceDetection'>;
}
declare module 'face-api.js/build/commonjs/factories/WithFaceExpressions.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/factories/WithFaceExpressions'>;
}
declare module 'face-api.js/build/commonjs/factories/WithFaceLandmarks.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/factories/WithFaceLandmarks'>;
}
declare module 'face-api.js/build/commonjs/factories/WithGender.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/factories/WithGender'>;
}
declare module 'face-api.js/build/commonjs/globalApi/allFaces.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/globalApi/allFaces'>;
}
declare module 'face-api.js/build/commonjs/globalApi/ComposableTask.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/globalApi/ComposableTask'>;
}
declare module 'face-api.js/build/commonjs/globalApi/ComputeFaceDescriptorsTasks.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/globalApi/ComputeFaceDescriptorsTasks'>;
}
declare module 'face-api.js/build/commonjs/globalApi/DetectFaceLandmarksTasks.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/globalApi/DetectFaceLandmarksTasks'>;
}
declare module 'face-api.js/build/commonjs/globalApi/detectFaces.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/globalApi/detectFaces'>;
}
declare module 'face-api.js/build/commonjs/globalApi/DetectFacesTasks.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/globalApi/DetectFacesTasks'>;
}
declare module 'face-api.js/build/commonjs/globalApi/extractFacesAndComputeResults.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/globalApi/extractFacesAndComputeResults'>;
}
declare module 'face-api.js/build/commonjs/globalApi/FaceMatcher.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/globalApi/FaceMatcher'>;
}
declare module 'face-api.js/build/commonjs/globalApi/index.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/globalApi/index'>;
}
declare module 'face-api.js/build/commonjs/globalApi/nets.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/globalApi/nets'>;
}
declare module 'face-api.js/build/commonjs/globalApi/PredictAgeAndGenderTask.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/globalApi/PredictAgeAndGenderTask'>;
}
declare module 'face-api.js/build/commonjs/globalApi/PredictFaceExpressionsTask.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/globalApi/PredictFaceExpressionsTask'>;
}
declare module 'face-api.js/build/commonjs/globalApi/types.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/globalApi/types'>;
}
declare module 'face-api.js/build/commonjs/index.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/index'>;
}
declare module 'face-api.js/build/commonjs/minBbox.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/minBbox'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/bgrToRgbTensor.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/bgrToRgbTensor'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/config.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/config'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/extractImagePatches.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/extractImagePatches'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/extractParams.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/extractParams'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/extractParamsFromWeigthMap.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/extractParamsFromWeigthMap'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/getSizesForScale.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/getSizesForScale'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/index.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/index'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/Mtcnn.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/Mtcnn'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/MtcnnBox.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/MtcnnBox'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/MtcnnOptions.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/MtcnnOptions'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/normalize.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/normalize'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/ONet.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/ONet'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/PNet.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/PNet'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/prelu.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/prelu'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/pyramidDown.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/pyramidDown'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/RNet.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/RNet'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/sharedLayers.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/sharedLayers'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/stage1.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/stage1'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/stage2.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/stage2'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/stage3.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/stage3'>;
}
declare module 'face-api.js/build/commonjs/mtcnn/types.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/mtcnn/types'>;
}
declare module 'face-api.js/build/commonjs/resizeResults.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/resizeResults'>;
}
declare module 'face-api.js/build/commonjs/ssdMobilenetv1/boxPredictionLayer.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/ssdMobilenetv1/boxPredictionLayer'>;
}
declare module 'face-api.js/build/commonjs/ssdMobilenetv1/extractParams.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/ssdMobilenetv1/extractParams'>;
}
declare module 'face-api.js/build/commonjs/ssdMobilenetv1/extractParamsFromWeigthMap.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/ssdMobilenetv1/extractParamsFromWeigthMap'>;
}
declare module 'face-api.js/build/commonjs/ssdMobilenetv1/index.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/ssdMobilenetv1/index'>;
}
declare module 'face-api.js/build/commonjs/ssdMobilenetv1/mobileNetV1.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/ssdMobilenetv1/mobileNetV1'>;
}
declare module 'face-api.js/build/commonjs/ssdMobilenetv1/nonMaxSuppression.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/ssdMobilenetv1/nonMaxSuppression'>;
}
declare module 'face-api.js/build/commonjs/ssdMobilenetv1/outputLayer.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/ssdMobilenetv1/outputLayer'>;
}
declare module 'face-api.js/build/commonjs/ssdMobilenetv1/pointwiseConvLayer.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/ssdMobilenetv1/pointwiseConvLayer'>;
}
declare module 'face-api.js/build/commonjs/ssdMobilenetv1/predictionLayer.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/ssdMobilenetv1/predictionLayer'>;
}
declare module 'face-api.js/build/commonjs/ssdMobilenetv1/SsdMobilenetv1.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/ssdMobilenetv1/SsdMobilenetv1'>;
}
declare module 'face-api.js/build/commonjs/ssdMobilenetv1/SsdMobilenetv1Options.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/ssdMobilenetv1/SsdMobilenetv1Options'>;
}
declare module 'face-api.js/build/commonjs/ssdMobilenetv1/types.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/ssdMobilenetv1/types'>;
}
declare module 'face-api.js/build/commonjs/tinyFaceDetector/const.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/tinyFaceDetector/const'>;
}
declare module 'face-api.js/build/commonjs/tinyFaceDetector/index.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/tinyFaceDetector/index'>;
}
declare module 'face-api.js/build/commonjs/tinyFaceDetector/TinyFaceDetector.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/tinyFaceDetector/TinyFaceDetector'>;
}
declare module 'face-api.js/build/commonjs/tinyFaceDetector/TinyFaceDetectorOptions.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/tinyFaceDetector/TinyFaceDetectorOptions'>;
}
declare module 'face-api.js/build/commonjs/tinyYolov2/const.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/tinyYolov2/const'>;
}
declare module 'face-api.js/build/commonjs/tinyYolov2/index.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/tinyYolov2/index'>;
}
declare module 'face-api.js/build/commonjs/tinyYolov2/TinyYolov2.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/tinyYolov2/TinyYolov2'>;
}
declare module 'face-api.js/build/commonjs/xception/extractParams.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/xception/extractParams'>;
}
declare module 'face-api.js/build/commonjs/xception/extractParamsFromWeigthMap.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/xception/extractParamsFromWeigthMap'>;
}
declare module 'face-api.js/build/commonjs/xception/index.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/xception/index'>;
}
declare module 'face-api.js/build/commonjs/xception/TinyXception.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/xception/TinyXception'>;
}
declare module 'face-api.js/build/commonjs/xception/types.js' {
  declare module.exports: $Exports<'face-api.js/build/commonjs/xception/types'>;
}
declare module 'face-api.js/build/es6/ageGenderNet/AgeGenderNet.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/ageGenderNet/AgeGenderNet'>;
}
declare module 'face-api.js/build/es6/ageGenderNet/extractParams.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/ageGenderNet/extractParams'>;
}
declare module 'face-api.js/build/es6/ageGenderNet/extractParamsFromWeigthMap.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/ageGenderNet/extractParamsFromWeigthMap'>;
}
declare module 'face-api.js/build/es6/ageGenderNet/index.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/ageGenderNet/index'>;
}
declare module 'face-api.js/build/es6/ageGenderNet/types.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/ageGenderNet/types'>;
}
declare module 'face-api.js/build/es6/classes/FaceDetection.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/classes/FaceDetection'>;
}
declare module 'face-api.js/build/es6/classes/FaceLandmarks.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/classes/FaceLandmarks'>;
}
declare module 'face-api.js/build/es6/classes/FaceLandmarks5.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/classes/FaceLandmarks5'>;
}
declare module 'face-api.js/build/es6/classes/FaceLandmarks68.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/classes/FaceLandmarks68'>;
}
declare module 'face-api.js/build/es6/classes/FaceMatch.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/classes/FaceMatch'>;
}
declare module 'face-api.js/build/es6/classes/index.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/classes/index'>;
}
declare module 'face-api.js/build/es6/classes/LabeledFaceDescriptors.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/classes/LabeledFaceDescriptors'>;
}
declare module 'face-api.js/build/es6/common/depthwiseSeparableConv.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/common/depthwiseSeparableConv'>;
}
declare module 'face-api.js/build/es6/common/fullyConnectedLayer.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/common/fullyConnectedLayer'>;
}
declare module 'face-api.js/build/es6/common/loadConvParamsFactory.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/common/loadConvParamsFactory'>;
}
declare module 'face-api.js/build/es6/dom/extractFaces.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/dom/extractFaces'>;
}
declare module 'face-api.js/build/es6/dom/extractFaceTensors.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/dom/extractFaceTensors'>;
}
declare module 'face-api.js/build/es6/dom/index.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/dom/index'>;
}
declare module 'face-api.js/build/es6/draw/drawContour.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/draw/drawContour'>;
}
declare module 'face-api.js/build/es6/draw/drawDetections.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/draw/drawDetections'>;
}
declare module 'face-api.js/build/es6/draw/drawFaceExpressions.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/draw/drawFaceExpressions'>;
}
declare module 'face-api.js/build/es6/draw/DrawFaceLandmarks.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/draw/DrawFaceLandmarks'>;
}
declare module 'face-api.js/build/es6/draw/index.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/draw/index'>;
}
declare module 'face-api.js/build/es6/euclideanDistance.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/euclideanDistance'>;
}
declare module 'face-api.js/build/es6/faceExpressionNet/FaceExpressionNet.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceExpressionNet/FaceExpressionNet'>;
}
declare module 'face-api.js/build/es6/faceExpressionNet/FaceExpressions.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceExpressionNet/FaceExpressions'>;
}
declare module 'face-api.js/build/es6/faceExpressionNet/index.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceExpressionNet/index'>;
}
declare module 'face-api.js/build/es6/faceFeatureExtractor/denseBlock.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceFeatureExtractor/denseBlock'>;
}
declare module 'face-api.js/build/es6/faceFeatureExtractor/extractorsFactory.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceFeatureExtractor/extractorsFactory'>;
}
declare module 'face-api.js/build/es6/faceFeatureExtractor/extractParams.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceFeatureExtractor/extractParams'>;
}
declare module 'face-api.js/build/es6/faceFeatureExtractor/extractParamsFromWeigthMap.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceFeatureExtractor/extractParamsFromWeigthMap'>;
}
declare module 'face-api.js/build/es6/faceFeatureExtractor/extractParamsFromWeigthMapTiny.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceFeatureExtractor/extractParamsFromWeigthMapTiny'>;
}
declare module 'face-api.js/build/es6/faceFeatureExtractor/extractParamsTiny.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceFeatureExtractor/extractParamsTiny'>;
}
declare module 'face-api.js/build/es6/faceFeatureExtractor/FaceFeatureExtractor.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceFeatureExtractor/FaceFeatureExtractor'>;
}
declare module 'face-api.js/build/es6/faceFeatureExtractor/index.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceFeatureExtractor/index'>;
}
declare module 'face-api.js/build/es6/faceFeatureExtractor/loadParamsFactory.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceFeatureExtractor/loadParamsFactory'>;
}
declare module 'face-api.js/build/es6/faceFeatureExtractor/TinyFaceFeatureExtractor.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceFeatureExtractor/TinyFaceFeatureExtractor'>;
}
declare module 'face-api.js/build/es6/faceFeatureExtractor/types.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceFeatureExtractor/types'>;
}
declare module 'face-api.js/build/es6/faceLandmarkNet/FaceLandmark68Net.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceLandmarkNet/FaceLandmark68Net'>;
}
declare module 'face-api.js/build/es6/faceLandmarkNet/FaceLandmark68NetBase.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceLandmarkNet/FaceLandmark68NetBase'>;
}
declare module 'face-api.js/build/es6/faceLandmarkNet/FaceLandmark68TinyNet.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceLandmarkNet/FaceLandmark68TinyNet'>;
}
declare module 'face-api.js/build/es6/faceLandmarkNet/index.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceLandmarkNet/index'>;
}
declare module 'face-api.js/build/es6/faceProcessor/extractParams.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceProcessor/extractParams'>;
}
declare module 'face-api.js/build/es6/faceProcessor/extractParamsFromWeigthMap.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceProcessor/extractParamsFromWeigthMap'>;
}
declare module 'face-api.js/build/es6/faceProcessor/FaceProcessor.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceProcessor/FaceProcessor'>;
}
declare module 'face-api.js/build/es6/faceProcessor/index.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceProcessor/index'>;
}
declare module 'face-api.js/build/es6/faceProcessor/types.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceProcessor/types'>;
}
declare module 'face-api.js/build/es6/faceProcessor/util.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceProcessor/util'>;
}
declare module 'face-api.js/build/es6/faceRecognitionNet/convLayer.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceRecognitionNet/convLayer'>;
}
declare module 'face-api.js/build/es6/faceRecognitionNet/extractParams.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceRecognitionNet/extractParams'>;
}
declare module 'face-api.js/build/es6/faceRecognitionNet/extractParamsFromWeigthMap.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceRecognitionNet/extractParamsFromWeigthMap'>;
}
declare module 'face-api.js/build/es6/faceRecognitionNet/FaceRecognitionNet.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceRecognitionNet/FaceRecognitionNet'>;
}
declare module 'face-api.js/build/es6/faceRecognitionNet/index.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceRecognitionNet/index'>;
}
declare module 'face-api.js/build/es6/faceRecognitionNet/residualLayer.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceRecognitionNet/residualLayer'>;
}
declare module 'face-api.js/build/es6/faceRecognitionNet/scaleLayer.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceRecognitionNet/scaleLayer'>;
}
declare module 'face-api.js/build/es6/faceRecognitionNet/types.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/faceRecognitionNet/types'>;
}
declare module 'face-api.js/build/es6/factories/index.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/factories/index'>;
}
declare module 'face-api.js/build/es6/factories/WithAge.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/factories/WithAge'>;
}
declare module 'face-api.js/build/es6/factories/WithFaceDescriptor.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/factories/WithFaceDescriptor'>;
}
declare module 'face-api.js/build/es6/factories/WithFaceDetection.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/factories/WithFaceDetection'>;
}
declare module 'face-api.js/build/es6/factories/WithFaceExpressions.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/factories/WithFaceExpressions'>;
}
declare module 'face-api.js/build/es6/factories/WithFaceLandmarks.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/factories/WithFaceLandmarks'>;
}
declare module 'face-api.js/build/es6/factories/WithGender.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/factories/WithGender'>;
}
declare module 'face-api.js/build/es6/globalApi/allFaces.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/globalApi/allFaces'>;
}
declare module 'face-api.js/build/es6/globalApi/ComposableTask.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/globalApi/ComposableTask'>;
}
declare module 'face-api.js/build/es6/globalApi/ComputeFaceDescriptorsTasks.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/globalApi/ComputeFaceDescriptorsTasks'>;
}
declare module 'face-api.js/build/es6/globalApi/DetectFaceLandmarksTasks.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/globalApi/DetectFaceLandmarksTasks'>;
}
declare module 'face-api.js/build/es6/globalApi/detectFaces.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/globalApi/detectFaces'>;
}
declare module 'face-api.js/build/es6/globalApi/DetectFacesTasks.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/globalApi/DetectFacesTasks'>;
}
declare module 'face-api.js/build/es6/globalApi/extractFacesAndComputeResults.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/globalApi/extractFacesAndComputeResults'>;
}
declare module 'face-api.js/build/es6/globalApi/FaceMatcher.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/globalApi/FaceMatcher'>;
}
declare module 'face-api.js/build/es6/globalApi/index.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/globalApi/index'>;
}
declare module 'face-api.js/build/es6/globalApi/nets.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/globalApi/nets'>;
}
declare module 'face-api.js/build/es6/globalApi/PredictAgeAndGenderTask.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/globalApi/PredictAgeAndGenderTask'>;
}
declare module 'face-api.js/build/es6/globalApi/PredictFaceExpressionsTask.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/globalApi/PredictFaceExpressionsTask'>;
}
declare module 'face-api.js/build/es6/globalApi/types.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/globalApi/types'>;
}
declare module 'face-api.js/build/es6/index.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/index'>;
}
declare module 'face-api.js/build/es6/minBbox.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/minBbox'>;
}
declare module 'face-api.js/build/es6/mtcnn/bgrToRgbTensor.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/bgrToRgbTensor'>;
}
declare module 'face-api.js/build/es6/mtcnn/config.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/config'>;
}
declare module 'face-api.js/build/es6/mtcnn/extractImagePatches.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/extractImagePatches'>;
}
declare module 'face-api.js/build/es6/mtcnn/extractParams.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/extractParams'>;
}
declare module 'face-api.js/build/es6/mtcnn/extractParamsFromWeigthMap.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/extractParamsFromWeigthMap'>;
}
declare module 'face-api.js/build/es6/mtcnn/getSizesForScale.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/getSizesForScale'>;
}
declare module 'face-api.js/build/es6/mtcnn/index.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/index'>;
}
declare module 'face-api.js/build/es6/mtcnn/Mtcnn.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/Mtcnn'>;
}
declare module 'face-api.js/build/es6/mtcnn/MtcnnBox.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/MtcnnBox'>;
}
declare module 'face-api.js/build/es6/mtcnn/MtcnnOptions.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/MtcnnOptions'>;
}
declare module 'face-api.js/build/es6/mtcnn/normalize.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/normalize'>;
}
declare module 'face-api.js/build/es6/mtcnn/ONet.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/ONet'>;
}
declare module 'face-api.js/build/es6/mtcnn/PNet.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/PNet'>;
}
declare module 'face-api.js/build/es6/mtcnn/prelu.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/prelu'>;
}
declare module 'face-api.js/build/es6/mtcnn/pyramidDown.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/pyramidDown'>;
}
declare module 'face-api.js/build/es6/mtcnn/RNet.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/RNet'>;
}
declare module 'face-api.js/build/es6/mtcnn/sharedLayers.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/sharedLayers'>;
}
declare module 'face-api.js/build/es6/mtcnn/stage1.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/stage1'>;
}
declare module 'face-api.js/build/es6/mtcnn/stage2.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/stage2'>;
}
declare module 'face-api.js/build/es6/mtcnn/stage3.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/stage3'>;
}
declare module 'face-api.js/build/es6/mtcnn/types.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/mtcnn/types'>;
}
declare module 'face-api.js/build/es6/resizeResults.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/resizeResults'>;
}
declare module 'face-api.js/build/es6/ssdMobilenetv1/boxPredictionLayer.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/ssdMobilenetv1/boxPredictionLayer'>;
}
declare module 'face-api.js/build/es6/ssdMobilenetv1/extractParams.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/ssdMobilenetv1/extractParams'>;
}
declare module 'face-api.js/build/es6/ssdMobilenetv1/extractParamsFromWeigthMap.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/ssdMobilenetv1/extractParamsFromWeigthMap'>;
}
declare module 'face-api.js/build/es6/ssdMobilenetv1/index.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/ssdMobilenetv1/index'>;
}
declare module 'face-api.js/build/es6/ssdMobilenetv1/mobileNetV1.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/ssdMobilenetv1/mobileNetV1'>;
}
declare module 'face-api.js/build/es6/ssdMobilenetv1/nonMaxSuppression.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/ssdMobilenetv1/nonMaxSuppression'>;
}
declare module 'face-api.js/build/es6/ssdMobilenetv1/outputLayer.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/ssdMobilenetv1/outputLayer'>;
}
declare module 'face-api.js/build/es6/ssdMobilenetv1/pointwiseConvLayer.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/ssdMobilenetv1/pointwiseConvLayer'>;
}
declare module 'face-api.js/build/es6/ssdMobilenetv1/predictionLayer.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/ssdMobilenetv1/predictionLayer'>;
}
declare module 'face-api.js/build/es6/ssdMobilenetv1/SsdMobilenetv1.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/ssdMobilenetv1/SsdMobilenetv1'>;
}
declare module 'face-api.js/build/es6/ssdMobilenetv1/SsdMobilenetv1Options.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/ssdMobilenetv1/SsdMobilenetv1Options'>;
}
declare module 'face-api.js/build/es6/ssdMobilenetv1/types.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/ssdMobilenetv1/types'>;
}
declare module 'face-api.js/build/es6/tinyFaceDetector/const.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/tinyFaceDetector/const'>;
}
declare module 'face-api.js/build/es6/tinyFaceDetector/index.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/tinyFaceDetector/index'>;
}
declare module 'face-api.js/build/es6/tinyFaceDetector/TinyFaceDetector.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/tinyFaceDetector/TinyFaceDetector'>;
}
declare module 'face-api.js/build/es6/tinyFaceDetector/TinyFaceDetectorOptions.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/tinyFaceDetector/TinyFaceDetectorOptions'>;
}
declare module 'face-api.js/build/es6/tinyYolov2/const.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/tinyYolov2/const'>;
}
declare module 'face-api.js/build/es6/tinyYolov2/index.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/tinyYolov2/index'>;
}
declare module 'face-api.js/build/es6/tinyYolov2/TinyYolov2.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/tinyYolov2/TinyYolov2'>;
}
declare module 'face-api.js/build/es6/xception/extractParams.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/xception/extractParams'>;
}
declare module 'face-api.js/build/es6/xception/extractParamsFromWeigthMap.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/xception/extractParamsFromWeigthMap'>;
}
declare module 'face-api.js/build/es6/xception/index.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/xception/index'>;
}
declare module 'face-api.js/build/es6/xception/TinyXception.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/xception/TinyXception'>;
}
declare module 'face-api.js/build/es6/xception/types.js' {
  declare module.exports: $Exports<'face-api.js/build/es6/xception/types'>;
}
declare module 'face-api.js/dist/face-api.js' {
  declare module.exports: $Exports<'face-api.js/dist/face-api'>;
}
declare module 'face-api.js/dist/face-api.min.js' {
  declare module.exports: $Exports<'face-api.js/dist/face-api.min'>;
}
declare module 'face-api.js/jasmine-node.js' {
  declare module.exports: $Exports<'face-api.js/jasmine-node'>;
}
declare module 'face-api.js/karma.conf.js' {
  declare module.exports: $Exports<'face-api.js/karma.conf'>;
}
declare module 'face-api.js/rollup.config.js' {
  declare module.exports: $Exports<'face-api.js/rollup.config'>;
}
declare module 'face-api.js/typedoc.config.js' {
  declare module.exports: $Exports<'face-api.js/typedoc.config'>;
}
