// flow-typed signature: 7a8eacc4b35a16889708a77a7ba471e9
// flow-typed version: <<STUB>>/react-webcam_v^1.1.1/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-webcam'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-webcam' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-webcam/dist/react-webcam' {
  declare module.exports: any;
}

declare module 'react-webcam/dist/react-webcam.min' {
  declare module.exports: any;
}

declare module 'react-webcam/jest.config' {
  declare module.exports: any;
}

declare module 'react-webcam/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-webcam/dist/react-webcam.js' {
  declare module.exports: $Exports<'react-webcam/dist/react-webcam'>;
}
declare module 'react-webcam/dist/react-webcam.min.js' {
  declare module.exports: $Exports<'react-webcam/dist/react-webcam.min'>;
}
declare module 'react-webcam/jest.config.js' {
  declare module.exports: $Exports<'react-webcam/jest.config'>;
}
declare module 'react-webcam/webpack.config.js' {
  declare module.exports: $Exports<'react-webcam/webpack.config'>;
}
