// flow-typed signature: 54ffb4e203436e2d7d22e3a5ec5d505a
// flow-typed version: <<STUB>>/react-number-format_v^4.0.7/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-number-format'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-number-format' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-number-format/custom_formatters/card_expiry' {
  declare module.exports: any;
}

declare module 'react-number-format/dist/react-number-format.es' {
  declare module.exports: any;
}

declare module 'react-number-format/dist/react-number-format' {
  declare module.exports: any;
}

declare module 'react-number-format/dist/react-number-format.min' {
  declare module.exports: any;
}

declare module 'react-number-format/example/src/index' {
  declare module.exports: any;
}

declare module 'react-number-format/lib/number_format' {
  declare module.exports: any;
}

declare module 'react-number-format/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-number-format/custom_formatters/card_expiry.js' {
  declare module.exports: $Exports<'react-number-format/custom_formatters/card_expiry'>;
}
declare module 'react-number-format/dist/react-number-format.es.js' {
  declare module.exports: $Exports<'react-number-format/dist/react-number-format.es'>;
}
declare module 'react-number-format/dist/react-number-format.js' {
  declare module.exports: $Exports<'react-number-format/dist/react-number-format'>;
}
declare module 'react-number-format/dist/react-number-format.min.js' {
  declare module.exports: $Exports<'react-number-format/dist/react-number-format.min'>;
}
declare module 'react-number-format/example/src/index.js' {
  declare module.exports: $Exports<'react-number-format/example/src/index'>;
}
declare module 'react-number-format/lib/number_format.js' {
  declare module.exports: $Exports<'react-number-format/lib/number_format'>;
}
declare module 'react-number-format/lib/utils.js' {
  declare module.exports: $Exports<'react-number-format/lib/utils'>;
}
