// flow-typed signature: a08483d9f27b0808b766ed47f95604b1
// flow-typed version: <<STUB>>/typeface-roboto_v^0.0.54/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-roboto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-roboto' {
  declare module.exports: any;
}
